# -*- coding: utf-8 -*-
"""Exp 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVBU5o961K2eY07OnuhXU2MQm2GznUPw

Exp-1 (Introduction to Python)
* Name-Yashasavi Jain
* PRN-25070123127
"""

x,y,z="Apple","Cherry","Orange"
print(x,y,z,sep="\n")

x,y,w,z=2,2.5,"Yash",True
print(type(x),type(y),type(w),type(z),sep="\n")

a,b=10,5
print("sum=",a+b)
print ("product=",a*b)
print ("subtraction=",a-b)
print ("division=",a/b)
print ("remainder=",a%b)
print ("power=",a**b)

a=int(input("Enter First number:"))
b=int(input("Enter Second number:"))
print("Sum=",a+b,"\nProduct=",a*b,"\nSubtraction=",a-b,"\nDivision=",a/b,"\nRemainder=",a%b,"\nPower=",a**b)

import math
r=float(input("Enter the radius of the circle:"))
area=math.pi*r**2
print("The Area of the circle is:",area)

import math
a=math.log10(10)
print(a)

a,b=10,5
if a>b:
  print("b is less than a")
else:
  print("b is greater than a")